# https://taskfile.dev

version: "3"

# load environment variables from .env.dev
dotenv: [".env.dev"]

tasks:
  # Run Go service
  service:
    desc: "Run Go API (go run main.go start)"
    dir: service
    cmds:
      - go run main.go start -c "../config.yaml"
    silent: false

  # Run SvelteKit frontend
  web:
    desc: "Run SvelteKit dev server (npm run dev -- --host)"
    dir: web
    cmds:
      - npm install
      - npm run dev -- --host
    silent: false

  register:
    desc: "Register a new user"
    dir: service
    cmds:
      - go run main.go register -c "../config.yaml" {{.CLI_ARGS}}
    silent: false