models:
  claude-4-sonnet:
    title: "Claude 4 Sonnet"
    description: "The latest model from Anthropic. Claude 4 Sonnet is a significant upgrade to Claude 3.7 Sonnet, delivering superior coding and reasoning while responding more precisely to your instructions."
    icon: "anthropic"
    name: "claude-sonnet-4-20250514"
    provider: "anthropic"
    features:
      has_vision: true
      has_pdf: true
    flags:
      is_premium: true
      is_recommended: true

  qwen3:
    title: "Qwen3"
    description: "An open source mixture-of-experts (MoE) language model developed by Alibaba Cloud, activating only 3 billion parameters out of a total of 30B. It comes in various sizes and is licenced under the Apache 2.0 license."
    icon: "qwen"
    name: "qwen3:30b"
    provider: "ollama"
    features:
      has_reasoning: true
    flags:
      is_open_source: true
      is_free: true

  gpt-4.1:
    title: "GPT-4.1"
    description: GPT-4.1 is a flagship large language model optimized for advanced instruction following, real-world software engineering, and long-context reasoning. It outperforms GPT-4o and GPT-4.5 across coding (54.6% SWE-bench Verified), instruction compliance (87.4% IFEval), and multimodal understanding benchmarks.
    icon: "openai"
    name: "gpt-4.1"
    provider: "openai"
    features:
      has_vision: true

  gemini-2.5-flash:
    title: "Gemini 2.5 Flash"
    description: "Google's latest fast model, known for speed and accuracy (and also web search!). Not quite as smart as Claude 3.5 Sonnet, but WAY faster and cheaper. Also has an insanely large context window (it can handle a lot of data)."
    icon: "gemini"
    name: "gemini-2.5-flash-preview-05-20"
    provider: "gemini"
    features:
      has_vision: true
      has_pdf: true
      has_search: true
      has_reasoning: true
      has_effort_control: true
    flags:
      is_fast: true
